"""Add headcount and current_headcount to Job model

Revision ID: d7915a860f03
Revises: 
Create Date: 2025-04-22 13:57:59.573825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7915a860f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headcount', sa.String(length=20), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('current_headcount', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True, server_default='0'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('title_zh',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_path')
        batch_op.drop_column('bio')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('title_zh',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('views')
        batch_op.drop_column('current_headcount')
        batch_op.drop_column('headcount')

    # ### end Alembic commands ###
